# Generated by Django 5.0.2 on 2024-02-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_friends"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="friends",
        ),
    ]
