# Generated by Django 5.0.2 on 2024-02-24 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboards", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connectionsscore",
            name="game",
        ),
    ]
