# Generated by Django 5.0.2 on 2024-02-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboards", "0002_remove_connectionsscore_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectionsscore",
            name="score_details",
            field=models.TextField(max_length=4),
        ),
    ]
