# Generated by Django 5.0.2 on 2024-02-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboards", "0003_alter_connectionsscore_score_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectionsscore",
            name="score_details",
            field=models.TextField(),
        ),
    ]
