# Generated by Django 5.0.2 on 2024-02-25 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0003_connectionsscore_raw_score_details'),
        ('leaderboards', '0004_alter_connectionsscore_score_details'),
    ]

    operations = [
    ]
