# Generated by Django 5.0.2 on 2024-02-25 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboards", "0005_merge_20240225_0402"),
        ("leaderboards", "0005_merge_20240225_0410"),
    ]

    operations = []
