# Generated by Django 5.0.2 on 2024-02-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0005_merge_20240225_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionsscore',
            name='score_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
