# Generated by Django 5.0.2 on 2024-02-25 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0006_connectionsscore_score_value'),
        ('leaderboards', '0006_merge_20240225_0527'),
    ]

    operations = [
    ]
