# Generated by Django 5.0.2 on 2024-02-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0007_merge_20240225_0849'),
        ('leaderboards', '0007_merge_20240225_0906'),
    ]

    operations = [
    ]
