# Generated by Django 5.0.2 on 2024-04-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0008_merge_20240225_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionsscore',
            name='score_comment',
            field=models.CharField(default='', max_length=10),
        ),
    ]
